"""Structured ENGLISH book - unique chapters, zero filler. Run: python src/generate_book_en.py"""
import os
BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT_MD = os.path.join(BASE, "book_en.md")
C = []
def part(title, deck):
    C.append(f"# {title}\n\n*{deck}*\n")
def chap(title, body):
    C.append(f"## {title}\n\n{body}\n")

part("How to use this book", "Start at Chapter 1. Each screen is one page. Use Contents any time. Numbers marked [UNVERIFIED] must be re-checked on the official page before you pay.")
chap("1. The 60-second decision", "**JEE is NOT compulsory.** Only JEE Advanced counts in Germany; Mains alone and EAMCET count for nothing.\n\n- **Three gates:** 1) Inter total 700+/1000 (70%) 2) MPC stream 3) German C1 for 95% of Bachelors (only TUM's BSc is fully English).\n- **Two roads, both 4 years:** A) Studienkolleg: Inter, free 1-year T-Kurs in Germany, FSP exam, Bachelor. B) Bridge: Inter, 1st-year Mech/Aero B.Tech in India, direct Bachelor Year-1.\n- **Money 2026:** blocked 11,904/yr (refundable monthly) + semester 97-440 + living 850-1500/mo + APS Rs 18k + IELTS Rs 17k + German to B1 about Rs 1.2L. Tuition: 0 except Stuttgart (1,500/sem) and TUM (3,000/sem BSc).\n- **Below 700/1000?** Both Bachelor roads close. Finish a full B.Tech, come for a Master instead.")
part("Part I - Foundations", "How Germany decides who may study. Read once, then use as reference.")
chap("2. Why Class 12 alone is never enough", "Germany's Abitur takes 13 school years; India's 10+2 takes 12. So DAAD's rule (verified on daad.in) is:\n\n- Indian Class 12 alone = NO direct Bachelor admission, from ANY board (TSBIE, CBSE, ICSE, AP).\n- Exactly three exceptions: **JEE Advanced rank** (direct, engineering only) / **1 completed Bachelor year** in the same field at a recognised university / **Studienkolleg + FSP pass**.\n- Every university is autonomous: it checks your file itself. APS only verifies documents; uni-assist only forwards them. Neither admits you.")
chap("3. The 70% rule (from winter 2026/27)", "Announced 23.02.2026, in Anabin since 15.03.2026:\n\n- You need **at least 70% of the maximum achievable overall marks in Class 12**, identical for CBSE/ICSE/State boards, for BOTH the Studienkolleg route and the 1-year bridge route.\n- It is the OVERALL percentage, not best-of-5. Grace-marks edge cases: confirm with info@aps-india.de.\n- Below 70%: do a full Indian degree first, then apply for a Master. Do not pay any agent promising otherwise.")
chap("4. APS: the mandatory stamp", "Since 01.11.2022 every Indian qualification needs APS (aps-india.de, Science Section, German Embassy Delhi). No APS = no uni-assist processing = no visa.\n\n- **Fee Rs 18,000, non-refundable.** Pay online via CCAvenue (auto-verified); manual transfers delay you.\n- **Steps:** eligibility quiz, pick the right procedure (Class XII / JEE / undergrad-2-semesters), register online, print + hand-sign, courier complete colour A4 copies (both sides) to Delhi. Never send originals unless asked.\n- **Time:** 3-4 weeks normal, 8-10 weeks in May-Aug / Oct-Feb. Apply 4-6 months before your university deadline.\n- **Trap:** applying after semester 1 and again after semester 2 means paying twice (the assessment category changes). Apply ONCE, when your stage is complete.\n- **Result:** a digital PDF with e-signature. Never rename, edit or merge it. Exemptions exist only for full degrees earned outside India, IB diplomas, and PhDs with supervisor confirmation.")
chap("5. Anabin H+ in 5 minutes", "Anabin (anabin.kmk.org) is the German database that says whether your Indian institution counts as a university.\n\n- Go to Institutionen, search country India, type your university's name (e.g. Jawaharlal Nehru Technological University Hyderabad).\n- **H+ = recognised.** H+/- = unclear, avoid for the bridge. H- = not recognised (APS may refuse a positive certificate).\n- The status that matters is the **degree-awarding** university, not your college building. Affiliated colleges inherit it only if that university is H+. Screenshot and print the H+ page for your file.")
chap("6. Uni-assist and the VPD", "180+ universities outsource document screening to uni-assist (my.uni-assist.de). TUM, RWTH and Stuttgart Aerospace Masters need a VPD if your degree is non-German.\n\n- Create one online application per study wish, upload PDFs (fully digital), pay (about 75 + 30 per extra wish [UNVERIFIED - check the pay page]), wait 4-6 weeks (Asia: 3-4).\n- You receive a **VPD PDF, valid 1 year for one specific university**. Uni-assist does NOT forward it: you apply YOURSELF on the university portal before its deadline, attaching the VPD + SOP/CV.\n- Real deadline math: VPD 6-8 weeks BEFORE the university deadline. A 15 July university deadline means your VPD application goes out in late May.")
part("Part II - Every aerospace college", "English options first, then German. One chapter per real choice.")
chap("7. English Bachelor: TUM Aerospace B.Sc.", "The ONLY fully English Aerospace Bachelor in Germany. Garching/Ottobrunn near Munich. 6 semesters, 180 ECTS, winter intake only (apply roughly 15.05-15.07).\n\n- **Cost:** 3,000/semester tuition (non-EU since WS24/25) + 97 contribution = about 18,582 for 3 years + Munich living (1,200-1,500/mo).\n- **Entry:** English B2 + German A2 mandatory (Goethe A2 etc.) + aptitude assessment + 8-week pre-internship (2 weeks before end of semester 2 at latest).\n- **Still needs:** a valid HZB path (Kolleg/1-year/JEE) - English does not waive it. Official: tum.de Aerospace B.Sc. page.")
chap("8. English Masters I: Bremen + Darmstadt (FREE)", "**Uni Bremen Space Engineering M.Sc.** - the best free English value. 4 semesters, 100% English, 0 tuition + ~425/sem contribution. Needs C1 English (waived if your last degree was in English), an engineering/physics Bachelor with 24+ CP aero content, an online entrance test and a motivation letter. Local NC, max 30/semester. Apply roughly 15.03-30.04.\n\n**TU Darmstadt Aerospace M.Sc.** - the TU9 English Master. 4 semesters, 120 ECTS, 0 tuition, English C1. Entry includes a 2-hour online exam over 7 topics (mechanics, thermo, machine elements, control, measurement, numerics, fluids). Winter + summer intake.")
chap("9. English Masters II: FH Aachen + Wuerzburg + BTU (FREE)", "**FH Aachen Aerospace M.Sc.** - 3 semesters, English (1-2 modules German), 0 tuition. Needs a 7-semester/210 ECTS relevant Bachelor + IELTS 6.5/TOEFL 92 + GRE quantitative 83rd percentile for non-EHEA degrees. Non-EU deadlines 31.05 (winter) / 30.11 (summer).\n\n**JMU Wuerzburg Aerospace Informatics / Satellite Tech Elite** - 4 semesters, English from B2 level (IELTS 6.0/TOEFL 72), 0 tuition, plus German A2 by end of semester 2. Built on real pico-satellite projects (13+ own satellites in orbit).\n\n**BTU Cottbus Transfers-Fluids-Materials** - joint degree Bordeaux/Louvain/Cottbus, 4 semesters with mobility, English IELTS 6.0, 0 tuition + mobility costs. Scholarship deadline January, self-funded March.")
chap("10. Expensive English Masters (backups only)", "**TUM Aerospace M.Sc. / ESPACE** - 6,000/semester (about 24,388 for 2 years), IELTS 6.5/TOEFL 88, aptitude assessment. Pay for the brand and Munich industry.\n\n**TU Berlin MSE Space Engineering** - continuing-education Master, 24,900 total + organisation fee, needs 1 year of practical experience. A backup, not a first choice.")
chap("11. German TUs: the big five", "All need German C1 (DSH-2/TestDaF 4x4) and a Kolleg/1-year/JEE path. All are 0 tuition except Stuttgart.\n\n- **RWTH Aachen LRT M.Sc.** - 3 semesters, 90 ECTS, German with some English. Needs 145 CP engineering background, 20-week internship, GRE for non-EU applicants [verify currency]. No extra non-EU tuition.\n- **Uni Stuttgart LRT B.Sc./M.Sc.** - the classic. B.Sc. has NC (selection via DoSV); 1,500/semester non-EU tuition (Baden-Wuerttemberg law) + 184 contribution.\n- **TU Berlin LRT M.Sc.** - open admission + subject fitness, winter/summer, ~379 contribution.\n- **TU Braunschweig LRT M.Sc.** - open admission, sits at the research airport with DLR next door.\n- **TU Hamburg (TUHH) Aviation M.Sc.** - open admission, German B2.2 at application rising to C1 at enrolment.\n- **TU Dresden** - keeps the traditional 10-semester Diplom in Mechanical with aerospace specialisation + newer Master structures; check SINS for exact rules.")
chap("12. Fachhochschulen: the practical road", "Small cohorts (~40:1 vs 200:1 at TUs), ex-industry professors, a MANDATORY 20-22-week industry semester built into the degree (it does not eat your 140-day work quota), and a direct pipeline to Airbus/Lufthansa Technik/MTU/Diehl. An FH Master is legally equal for industry and the Blue Card; only a direct PhD needs a cooperating TU supervisor.\n\n- **HAW Hamburg Aircraft Engineering** - 7 semesters incl. 22-week internship, 397/sem incl. Deutschland ticket, German C1 + English B1. Sits next to the Airbus A320 final assembly line.\n- **HS Bremen** - ILST Bachelor (German) + Aerospace Technologies Master (sem 1 German C1, sem 2-3 English) + fee-based Aeronautical Management M.Eng in English (9,800 total + 1 year aviation experience).\n- **HM Munich / THI Ingolstadt** - solid German-taught Bavarian options near MTU/Airbus Defence (note Munich non-EU fees at HM: 500/700 per semester).\n- **TH Wildau AVIMA** - English aviation-management Master (11-12.5k total + 1 year experience), management not engineering.\n- **DHBW Friedrichshafen (dual)** - paid study with Airbus DS: you need the company contract 12-18 months BEFORE enrolment, interviews mostly in German B2-C1. Without that contract it is not an option from India.")
chap("13. What to exclude (and why)", "- **UniBw Munich Aerospace** - officers/soldiers only, German only. No Indian self-funded route.\n- **Private universities (Constructor/IU/SRH/GISMA/Lancaster)** - NO pure aerospace degree; closest are Robotics/Mechatronics at 10-27k/year. Never pay that for a non-aerospace degree.\n- **TU Delft** - Netherlands, different country and system. **TUM Asia Singapore** - not Germany.\n- **Worms/Frankfurt Aviation Management, Wildau AVIMA** - business degrees, not engineering; they do not qualify you as an aerospace engineer.\n- **Lilium** (insolvent Oct 2024, ceased Dec 2024) - do not plan your career around it. **Volocopter** - near-zero hiring. **ESA staff posts** - require ESA-member citizenship; Indians enter via contractors or DLR.")
part("Part III - Money", "Budgets a parent can verify line by line.")
chap("14. Tuition and semester fees", "Federal default: 0 tuition, only the semester contribution (student services + student body + Deutschland semester ticket).\n\n- TUM: Bachelor 2,000/3,000 per program, Master 4,000/6,000 (Aerospace BSc 3,000; MSc/ESPACE 6,000) + 97. Fixed for standard duration + 1 semester per cohort; waivers 500-1,800/semester exist.\n- Baden-Wuerttemberg (Stuttgart/KIT/HKA/DHBW): 1,500/semester non-EU + ~184 contribution. Exempt: EU/EEA, German Abitur holders, settlement-permit holders, refugees.\n- Examples WS25/26: RWTH ~298, TU Berlin 379.06 (50 admin + 14.56 student + 85 Werk + 226.80 ticket + 2.70 fund), Braunschweig 440, Hamburg 384, HAW 397, Bremen ~380-425.\n- Second degrees in BW 650/semester; long-term fees in Lower Saxony 500/semester after standard duration + 6.")
chap("15. Blocked account 2026", "Student visa: **11,904/year = 992/month**, unchanged since Sep 2024 (no 2026 rise announced). Chancenkarte/job-seeker: 13,092 (1,091/month). Always transfer 100-150 extra as buffer (about 12,050).\n\n- **Expatrio:** 119 setup + 9/month (tariff since 07.07.26). **Fintiba:** Basic 89 + 4.90/month, Plus 277.80 incl. insurance (fastest confirmation for tight appointments). Deutsche Bank: 150 by post, 4-8 weeks, too slow unless early. **Coracle: stopped new accounts in 2025 - walk away if any agent offers it.**\n- Money must come from you or close family (friends/business transfers get rejected). It covers year 1 only. Open it AFTER admission (refunds take 4-8 weeks) but 8-12 weeks before the visa appointment.")
chap("16. Living costs by city", "DAAD baseline: 900-1,200/month needed; visa minimum 992 is NOT Munich-realistic.\n\n- **Munich 1,200-1,500** (dorm avg 400.60 with 1-7 semester waitlist; WG 550-900; plan 1,500).\n- **Stuttgart 1,000-1,300** (dorm 280-505). **Berlin 1,000-1,300** (WG 400-650). **Hamburg 950-1,250.** **Aachen 850-1,000** (WG 250-450, most affordable aero cluster). **Braunschweig/Bremen 850-1,050.**\n- Groceries 200-300 (Aldi/Lidl), Mensa meals 2.50-5, dorm vs WG makes the biggest difference. Apply for Studierendenwerk housing the day you get admission.")
chap("17. Health insurance + tickets", "Under 30 and enrolled = public insurance compulsory (TK/AOK/Barmer). 2026 TK: **141.16 (<23 or with child) / 146.29 (23+ childless)** per month = 110.38 health incl. 2.69% extra + 30.78/35.91 care. AOK same; Barmer/DAK slightly higher. Over 30 or 14+ semesters: voluntary ~220 + 47-55. Private over-30 tariffs from ~79-129 (under 45).\n\n- Deutschland ticket: 63/month from 01.01.2026 (was 49, then 58). Semester ticket about 208.80-226.80/semester; TUM's Bavarian ticket is separate from the 97. Broadcast fee (Rundfunkbeitrag): 18.36/month per flat, split in a WG.")
chap("18. Taxes on student jobs", "Minijob 2026: **603/month (7,236/year)** at 13.90/hour minimum wage (14.60 already locked for 2027). Midijob range 603.01-2,000 with sliding contributions. A minijob is free of health/care/unemployment insurance; pension is compulsory (3.6% yourself unless exempted).\n\n- **Werkstudent privilege:** max 20h/week during lectures, unlimited in holidays inside the day-cap, max 26 weeks/182 days over 20h per rolling year; only pension is deducted. Lose the 20h discipline and you lose student insurance status.\n- Single with no kids = tax class I automatically; second job = class VI (highest). Basic tax-free allowance 12,348 (2026); withholding above it is refunded by filing (4 years retroactive). Solidarity surcharge is ~0 for students. Deduct semester fees, books and travel.")
part("Part IV - The Telangana playbook", "TSBIE specifics, then the two roads in full.")
chap("19. TSBIE decoded", "Telangana State Board of Intermediate Education, Nampally Hyderabad (tsbie.cgg.gov.in - portal address migrates, check both TSBIE/TGBIE spellings). Inter 1st year (Class 11) 500 + 2nd year (Class 12) 500 = **1000 total**. Only **MPC** (Maths/Physics/Chemistry) qualifies for aerospace; BiPC/MEC/CEC do not.\n\n- Subjects: English + second language + Maths IA/IB + IIA/IIB + Physics + Chemistry + practicals. Use the printed maximum on YOUR long memo for the percentage, never memory.\n- Documents you will collect: Y1 short memo + Y2 short memo + LONG consolidated memo (via college, months later) + pass certificate + TC from the principal + study/conduct certificate + SSC memo + English-medium certificate. 10+ colour copies + 300 dpi uncropped PDF scans, no passwords.")
chap("20. Road A: Studienkolleg, step by step", "For students who can reach German B1 within ~9 months of Inter and move to Germany within a year.\n\n1. Inter result (Apr/May): compute %, chase long memo + pass certificate (TS colleges delay to Aug-Sep).\n2. German A1 to B1 intensive + IELTS 6.5 in parallel.\n3. APS XII-procedure (leave JEE blank), pre-alerting principal + TSBIE.\n4. TestAS Core + Engineering (target 110+) + VPD via uni-assist.\n5. Apply to 3-5 public Kollegs (15.07 / 15.01) - T-Kurs for university aero, TI-Kurs for FH.\n6. Aufnahmepruefung in Germany (invitation = visa basis) - German onSET + class-11 Maths.\n7. Kolleg, 2 semesters, ~32 hrs/week, free + ~300/semester.\n8. FSP in June/July (German 4.5h + Maths 180 min + Physics 180 min + oral).\n9. Bachelor application with FSP + C1 - start October.\n- English Kolleg alternatives (rare, fee-based): FH Aachen Freshman, Constructor Foundation (~12-13k/year).")
chap("21. Road B: the 1-year bridge, step by step", "For students whose German is zero now, who missed Kolleg deadlines, or who want an Indian backup.\n\n1. After Inter (70%+), join 1st-year B.Tech Mechanical/Aerospace/Mechatronics/Electrical at an H+ university: NIT-W, JNTUH-CEH, OUCE, then CBIT/Vasavi/MGIT if JNTUH/OU-awarded. Check anabin yourself; never trust a brochure.\n2. Finish BOTH semesters, no backlogs, aim 8.0+ CGPA. Mech-to-Aero is accepted; CSE-to-Aero is NOT (wrong field - rejection or Kolleg anyway). Never take CSE as an easy-CGPA shortcut.\n3. Learn German A1 to B2 + IELTS 6.5 during that year; keep stamped syllabus copies for the ECTS audit.\n4. ONE APS undergrad-2-semesters application AFTER year 1, then VPD, then direct Bachelor Year-1. No Kolleg.\n- Cost logic: government bridge (~Rs 1-1.5L) saves a ~11-12k EUR Kolleg living year. Costly private bridges (BITS/VIT-level fees) erase the saving.")
chap("22. Hyderabad practical guide", "German: Goethe-Zentrum Hyderabad + TestDaF/telc planning 3-4 months ahead (May-Aug fills first). IELTS: IDP/BC centres (Begumpet, Kukatpally, Dilsukhnagar), Academic centre-based, never home editions. VFS Hyderabad (Punjagutta Metro) serves the Chennai German mission covering Telangana - always follow the CSP letter, never book Delhi/Mumbai links. Blocked funding via SBI/HDFC/ICICI LRS (A2 form, PAN, admission letter) from self/parents only. Memo delays: Narayana/Chaitanya long memos + pass certificates often slip to Aug-Sep - APS needs the LONG memo, so chase from June. Name initials: align passport + APS + uni-assist exactly via affidavit BEFORE APS. EAMCET rank: useless for Germany, never mention it in the SOP.")
part("Part V - Language exams", "What to book, in what order, at what cost.")
chap("23. German levels and costs", "Degree taught in German needs C1: TestDaF 4x4 / DSH-2 (Germany only) / Goethe C1 / telc C1 Hochschule / OESD C1. Kolleg application needs B1 on paper; passing the entrance realistically needs B2.\n\n- Hyderabad prices: A1/A2/B1 Rs 27,730 per level at Goethe; exams A1 9,400 / A2 10,600 / B1 18,800 (or 4,700 per module retake) / B2 21,200 / C1 24,000. Total A1 to B1 about Rs 83,190 + 38,800 exams.\n- Zero to B1: 6-9 months intensive (620-1,100 hours with self-study). Zero to C1: 12-18 months, 800-1,000+ hours. Private institutes are cheaper but the VISA needs a Goethe/telc/TestDaF centre certificate - a private internal certificate is worthless at the mission.\n- Never book TestDaF below solid B2: it is one single exam with no module retakes (unlike Goethe/telc).")
chap("24. TestAS and IELTS", "TestAS (testas.de): Core module (quantitative/logical, 110 min paper) + Engineering subject module (45 tasks/145 min) for Aerospace. Choose the module at registration - it locks. English or German, about 4.5 hours. Standard scores 70-130 (mean 100): target 110+ competitive, 115+ for TUM/RWTH/KIT or to compensate a CGPA under 7. Dates: 24.10.26 / 26.11.26 / 25.02.27; book 8-10 weeks ahead. JEE holders may be exempt at some universities - confirm each.\n\n- IELTS Academic 6.0-7.0 / TOEFL iBT 80-100 is the published band (TUM 6.5/88, Bremen C1 ~7.0/95, Wuerzburg/BTU 6.0/72-79). Book centre-based Academic (~Rs 17k); keep the certificate under 1 year old for the visa unless the admission letter confirms your level. MOI letters sometimes unlock ADMISSION (Bremen accepts last-degree-in-English; Constructor accepts 6-year English) but almost never the VISA.")
part("Part VI - The visa chain", "Paperwork in exact order. One mistake costs months.")
chap("25. Blocked, insurance, uni-assist timing", "Open the blocked account AFTER admission (refunds take 4-8 weeks on failure) but 8-12 weeks before the visa slot. Add travel/incoming insurance (30k Schengen minimum for the gap) plus the public insurer confirmation (TK/AOK/Barmer ~140-160/month from semester start) needed for enrolment.\n\n- Uni-assist document rules (India): Class 12 certificate in original language (+ sworn translation only if not English/German), the APS PDF uploaded unmodified (it is verifiable online), full transcripts with the grading-scale page, language certificate, passport page, plus program extras (CV/SOP/LOR/internships). Scans: complete, uncropped, legible at 100%, PDF, no password.")
chap("26. CSP, VFS and the interview", "Since Jan 2025 everything runs via the Consular Services Portal (digital.diplo.de): upload the 10-slot Study-APS file (passport, Class 12, APS, admission, signed motivation, tabular CV, language, finance, insurance, degrees/VPD), pass the pre-check, then book biometrics ONLY via the CSP link. Fee 75 EUR (~Rs 8,500) + VFS ~Rs 2,500. Processing is officially 6-8 weeks, realistically 8-12 in India at peak (Chennai/Bengaluru have hit 8-12-week waits). Start 6-8 months before classes.\n\n- The 5-15 minute interview checks four things: genuine student, researched course (name modules + a lab), solid finance (blocked + sponsor + monthly payout math), coherent plan. Explain a gap year with certificates (German + TestAS + APS dates); identical dates across CV/SOP/CSP. Fake documents mean a ban plus a report to German authorities.")
chap("27. SOP, CV and LOR that work", "SOP 500-800 words (some programs cap at 1 page or 1,000-3,000 characters - the program page binds, and TUM runs plagiarism checks): fit + academic readiness + career rationale. Formal, factual, no hardship narrative, no CV repetition, no copied web text; name 3-4 modules plus professors/labs. Uni-assist does NOT evaluate it - it goes to the university WITH the VPD. The visa motivation letter is separate (why Germany + program + finance + post-plan, signed, consistent with the CV).\n\n- LORs: 2-3 academic (professors/supervisors), letterhead + signature, specific examples + rank/context + research aptitude. Request in October for summer intake. CV: tabular 1-2 pages, 11-12 pt, reverse chronological, uniform MM/YYYY, education first for recent graduates, 3-5 relevant courses with outcomes, tools, languages with CEFR + scores + dates. No Canva graphics, star bars or photos unless asked.")
part("Part VII - After the degree", "Scholarships first, then work, residence and employers.")
chap("28. Scholarships that fit Indians", "DAAD EPOS (Bachelor + 2 years experience, DAC list incl. India, 992/month Master, 1,300 PhD + travel + 460/year + insurance, apply direct to the listed course, mostly Aug-Nov). DAAD WISE (IIT/NIT/IISER/BITS 5th-6th sem, find the German professor yourself, 2-3 months May-Aug, ~692-750/month + 1,200 travel). Deutschlandstipendium 300/month (150 federal + 150 private sponsor, all nationalities, no income test, no repayment, awarded by the university itself - TUM ~800/year). Erasmus Mundus Joint Masters (study in 2+ EU countries, 1,400/month up to 24 months + tuition; India is the world's #1 recipient). Party foundations (Boell/KAS/Ebert/Luxemburg: ~992/month + extras, need B2 German + civic engagement + 1 Sept / 1 Mar / 15 July deadlines). Company/aero: DLR-DAAD fellowships (thesis 9 mo 992; doctoral 36 mo 1,760; postdoc 2,400), Munich Aerospace PhD (1,575/month, 3 years), TUM international one-off 500-1,800/semester.")
chap("29. Work rules 2024-2026", "Permits issued after 1 March 2024: 140 full / 280 half days per calendar year (was 120/240). Full = over 4 hours, half = up to 4 hours. Alternative counting: 20h/week = 2.5 days; the mission applies whichever is more favourable weekly. HiWi jobs at the university/Studierendenwerk/AStA + compulsory internships are UNLIMITED and uncounted; voluntary internships count; freelancing needs permission.\n\n- The 20h lecture-period rule (social law): stay at or under 20h to keep the Werkstudent privilege (no health/care/unemployment deductions, pension only). Over 20h is allowed on weekends/evenings/nights up to 26 weeks/182 days per year, and full-time in semester breaks inside the 140-day cap. Minimum wage: 12.82 (2025), 13.90 (2026), 14.60 (2027 locked). 20h x 13.90 = about 1,204/month gross.")
chap("30. Post-study to Blue Card to PR", "Graduation gives an 18-month one-off non-extendable job-seeker permit (any gainful work allowed while you search for a qualified job; apply before the student permit expires; >6 months abroad kills it without prior permission).\n\n- EU Blue Card thresholds: 2025: 48,300 regular / 43,759.80 shortage+new-grads; 2026: 50,700 / 45,934.20 (BMI announcement, federal gazette 31 Dec). MINT engineers ARE shortage occupations. Needs a recognised degree (Anabin H+ / ZAB), a 6-month+ matching contract; regular needs no agency approval. Max 4 years (contract + 3 months); job changes in the first 12 months need approval.\n- Settlement: general 5 years (study counts half) + 60 pension months + B1; skilled 4 years; Blue Card 21 months with B1 / 27 with A1 (reduced from 33 in March 2024 - many sites still print 33). Citizenship reform of 27 June 2024: 5 years (was 8) + B1 + self-support + test; 3-year exceptional track exists but the 2025 coalition plans to abolish it - check BMI. Germany now allows dual citizenship in principle, but INDIA does not: acquiring German means losing Indian (OCI possible).")
chap("31. Employers and the clearance wall", "Civil Airbus Commercial (Hamburg-Finkenwerder A320 line, Bremen wings), MTU civil engines (Munich/Hannover), civil DLR institutes, Isar Aerospace Ottobrunn (English-first NewSpace, 50+ openings, visa sponsorship possible for scarce skills), OHB Bremen (200+ openings incl. working students), Diehl Aviation, consultancies like ALTEN (common Indian entry point) - all open. Typical Werkstudent pay 15-18/hour; traditional OEMs want B1-B2 German + CATIA/MATLAB/Python; combine internship + thesis (Airbus allows it); ~75% of offers come via a prior internship.\n\n- The wall: Airbus Defence sites (Manching, Donauwoerth military), MTU military engines, Hensoldt, Diehl Defence, defence-adjacent DLR and secure OHB satcom frequently advertise EU-citizen/NATO-only (export control/ITAR/EAR, US taint, security vetting UES S1-S3). Strategy: target civil first, disclose nationality early, ask whether export-control vetting applies, build German + a clean internship record, convert after settlement.")
part("Part VIII - Your wall plans", "Print this part.")
chap("32. The 12-month master plan", "Inter 2026 batch targeting winter 2027 (summer 2027 only if everything compresses to January - treat as backup).\n\n- NOW-Sep 26: compute % (need 700+), anabin + myguide.de shortlist of 6-8 programs, start German intensive to B1, book TestAS Engineering + IELTS 6.5, request LORs, draft SOP/CV, collect module descriptions. By 15.09.26: dMAT registration IF doing an English/business Master for SS27+ (test 26.09, cert 12.10) + APS courier (can precede the dMAT cert).\n- Oct-Nov 26: APS chase (alert your college), VPD via uni-assist (4-6 weeks; TUM summer window 01.09-30.11 - submit early).\n- Dec 26-Jan 27: portals close ~15.01, admission letters Feb-Mar, blocked 11,904 + insurance immediately.\n- Feb-Mar 27: CSP Study-APS + VFS, visa wait. April 27: arrive, enrol with insurance proof, Anmeldung, start.\n- Budget: APS 18k + dMAT 150 + uni-assist ~75+30s + IELTS ~17k + visa 75+VFS + blocked 11,904 (refundable) + semester 144-395 (TUM 4-6k, Stuttgart 1.5k) + flight/insurance.")
chap("33. First 30 days + family budget + plan B", "Days 1-3: compute %, photograph every memo, passport check. Days 4-7: visit Goethe-Zentrum, book A1; book an IELTS date 3 months out; myguide.de shortlist of 8. Days 8-14: APS quiz + file start; meet the principal about the verification email; 2 hrs/day German. Days 15-30: A1 in full swing; TestAS Engineering samples; SOP v1; lock the Kolleg-vs-bridge decision.\n\n- One-time family spend: APS ~20k incl. courier, German to B1 ~1.2L, IELTS ~17k, TestAS/TestDaF ~14-17k, visa ~15k, flight 50-70k. Blocked 10.5-12.8L is refundable monthly, not a cost.\n- Plan B: below 70% = full B.Tech then English Master (Bremen/Darmstadt/FH Aachen, all free). Aufnahme failed = one retry next intake + private Kolleg as paid backup, keep pushing to B2. Visa rejected = no appeal exists; fix the stated reason (usually funds/language proof) and refile.")
part("Appendix", "Links, glossary, and the one-page checklist.")
chap("34. Links, glossary, final checklist", "Bookmark: aps-india.de (quiz/checklists/dmat) - daad.in bachelor pages - myguide.de - anabin.kmk.org - uni-assist.de - india.diplo.de - digital.diplo.de - visa.vfsglobal.com Chennai/Hyderabad - stk.kit.edu (T-Kurs/FSP) - testas.de - testdaf.de - hyderabad.german.in - make-it-in-germany.com (Blue Card, Chancenkarte) - arbeitsagentur.de.\n\n- Glossary: HZB = university entrance qualification. FSP = Feststellungspruefung (Kolleg final). VPD = preliminary documentation. Sperrkonto = blocked account. Anmeldung = city registration (14 days). eAT = electronic residence title. DoSV/hochschulstart = central admission portal. NC = restricted admission. Regelstudienzeit = standard duration.\n- Final checklist: SSC + Y1/Y2 long memos + pass cert + TC + study cert + same-name passport [ ] | % over 700 confirmed, route chosen, German seat booked [ ] | APS, TestAS 110+, IELTS 6.5, VPD 6-8 weeks pre-deadline [ ] | admission, blocked, TK/AOK, CSP, VFS, housing, Anmeldung, permit [ ].\n- Sources: APS India + DAAD India (live-fetched 17.09.26), KIT Studienkolleg (live), TK, German missions India, TestAS/TestDaF portals, 34 official .de program pages, DAAD/MyGermanUniversity databases. Re-verify every fee and deadline on the official page for YOUR intake - they shift yearly.")

def main():
    md = "\n".join(C) + "\n"
    with open(OUT_MD, "w", encoding="utf-8") as f:
        f.write(md)
    print(f"WROTE {OUT_MD} bytes={len(md.encode('utf-8'))} chapters={len(C)}")

if __name__ == "__main__":
    main()
