"""Generate 2000-page ENGLISH reference book. No deps. Run: python src/generate_book_en.py"""
import os
BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT_MD = os.path.join(BASE, "book_en.md")

PROGRAMS = [
 ("TUM Aerospace B.Sc.", "TU Munich, Garching/Ottobrunn, Bavaria", "B.Sc. 180 ECTS, 6 sem", "100% English (+ German A2 during studies)", "3000/sem + 97 contribution", "Winter only 15.05-15.07", "Aptitude test (EFV), no NC, 8-week internship", "https://www.tum.de/en/studies/degree-programs/detail/aerospace-bachelor-of-science-bsc"),
 ("TUM Aerospace M.Sc.", "TU Munich, Garching, Bavaria", "M.Sc. 120 ECTS, 4 sem", "German/English (full-English track possible, 70% EN)", "6000/sem + 97", "Winter 01.04-31.05, Summer 01.09-30.11", "Aptitude test (EV), IELTS 6.5 / TOEFL 88", "https://www.ed.tum.de/en/ed/studies/degree-programs/aerospace-m-sc"),
 ("TUM ESPACE", "TU Munich, Bavaria", "M.Sc. 120, 4 sem", "100% English, IELTS 6.5 / TOEFL 88", "6000/sem + 97", "Winter only 01.01-31.05", "Essay 500-700 words + aptitude", "https://www.ed.tum.de/en/ed/studies/degree-programs/earth-oriented-space-science-and-technology-m-sc"),
 ("TU Darmstadt Aerospace M.Sc.", "Darmstadt, Hessen", "M.Sc. 120, 4 sem", "English C1", "0 + ~300", "Winter+Summer 15.07/15.01", "2-hour online exam, 7 topics", "https://www.tu-darmstadt.de/studieren/studieninteressierte/studienangebot_studiengaenge/studiengang_277056.en.jsp"),
 ("RWTH Aachen Aerospace M.Sc.", "Aachen, NRW", "M.Sc. 90, 3 sem", "German C1 (+ some English)", "0 + ~315", "Winter+Summer", "145 CP Mech background, GRE for non-EU, 20-week internship", "https://www.rwth-aachen.de/"),
 ("TU Berlin Aerospace M.Sc.", "Berlin", "M.Sc. 120, 4 sem", "German (many English modules)", "0 + ~321-379", "Winter 31.08 Summer 28.02", "Open admission, subject fitness", "https://www.tu.berlin/"),
 ("TU Berlin MSE Space (continuing)", "Berlin", "M.Sc. 120, 4 sem hybrid", "English B2 + 1-year experience", "6225/sem (24,900 total)", "Winter 15.05 Summer 15.01", "Bachelor + work experience", "https://mse.tu-berlin.de/"),
 ("Uni Stuttgart Aerospace B.Sc.", "Stuttgart-Vaihingen, BW", "B.Sc. 180, 6 sem", "German", "1500 + 184", "Winter 15.07, restricted", "DoSV + pre-internship", "https://www.uni-stuttgart.de/en/study/bachelor-programs/aerospace-engineering-b.sc./"),
 ("Uni Stuttgart Aerospace M.Sc.", "Stuttgart, BW", "M.Sc. 120, 4 sem", "German", "1500 + 184", "Winter+Summer", "Aptitude test", "https://www.student.uni-stuttgart.de/studiengang/Luft--und-Raumfahrttechnik-M.Sc./"),
 ("TU Braunschweig Aerospace M.Sc.", "Braunschweig, NI", "M.Sc. 120, 4 sem", "German", "0 + ~375", "Winter 30.06 Summer 15.01, open", "Relevant Bachelor needed", "https://www.tu-braunschweig.de/studienangebot/luft-und-raumfahrttechnik-master"),
 ("TU Dresden Diploma/M.Sc.", "Dresden, SN", "Diploma 10 sem / M.Sc.", "German", "0 + ~300", "Winter", "Via SINS portal", "https://tu-dresden.de/ing/maschinenwesen/ilr/studium/studiengaenge"),
 ("TUHH Aviation M.Sc.", "Hamburg-Harburg", "M.Sc. 120, 4 sem", "German (some English), B2.2 to C1", "0 + ~332", "Winter+Summer 15.07/15.01, open", "BSc Mechanical", "https://www.tuhh.de/"),
 ("FH Aachen B.Eng.", "Aachen, NRW", "B.Eng. 210, 7 sem", "German (+ English)", "0 + ~300", "Winter 15.07/31.08, open", "8-week pre-internship", "https://www.fh-aachen.de/"),
 ("FH Aachen M.Sc.", "Aachen, NRW", "M.Sc. 90/120, 3-4 sem", "English (1-2 modules German)", "0 + ~300", "Winter+Summer, non-EU 31.05/30.11", "GRE Quant 83% + IELTS 6.5 / TOEFL 92", "https://www.fh-aachen.de/en/studies/degree-programmes/aerospace-engineering-msc"),
 ("HAW Hamburg Aircraft Eng.", "Hamburg", "B.Eng. 210, 7 sem + 22-week industry phase", "German C1 + English B1", "0 + 397 incl. ticket", "Winter+Summer 01.06-15.07 via DoSV", "NC via hochschulstart", "https://www.haw-hamburg.de/en/bachelor-aeronautical-engineering/"),
 ("HAW Hamburg M.Sc.", "Hamburg", "M.Sc. 90, 3 sem", "German + English B1", "0 + 397", "Winter+Summer", "210 CP + grade 2.5", "https://www.haw-hamburg.de/master-flugzeugbau"),
 ("HS Bremen Aviation B.Eng.", "Bremen", "B.Eng. 210, 7 sem", "German", "0 + ~380", "Winter 01.06-15.07", "Open admission", "https://www.hs-bremen.de/en/"),
 ("HS Bremen Aerospace Tech M.Sc.", "Bremen", "M.Sc. 90, 3 sem", "German sem 1 + English sem 2-3 (needs DE C1 + EN B2)", "0 + ~380", "Winter+Summer", "210 CP or 180 + 20-week internship", "https://www.hs-bremen.de/en/study/degree-programme/aerospace-technologies-msc/"),
 ("HS Bremen Aviation Mgmt M.Eng.", "Bremen IGC", "M.Eng. 60, 2 sem", "English + 1-year aviation experience", "9,800 total", "Winter", "Work experience", "https://www.hs-bremen.de/en/study/degree-programme/aeronautical-management-meng/"),
 ("HM Munich B.Sc.", "Munich, BY", "B.Sc. 210, 7 sem incl. internship", "German", "0 (non-EU 500) + ~150", "Winter+Summer 02.05-15.07", "Open 23/24 + 8-week + 20-week internship sem 5", "https://www.hm.edu/"),
 ("HM Munich M.Sc.", "Munich, BY", "M.Sc. 3 full-time / 6 part-time sem", "German (partly English)", "0 (non-EU 700)", "Winter+Summer", "NC grade 2.5", "https://www.hm.edu/"),
 ("THI Ingolstadt B.Eng.", "Ingolstadt, BY", "B.Eng. 210, 7 sem", "German", "0 + ~150", "Winter, open", "Via PRIMUSS", "https://www.thi.de/"),
 ("THI M.Eng.", "Ingolstadt", "M.Eng. 90, 3/6 sem", "German", "0 + ~150", "Winter+Summer, NC", "STEM Bachelor", "https://www.thi.de/"),
 ("THI Intelligent Aerial Systems", "Ingolstadt", "M.Eng. 4 sem", "English B2 + German A1 by sem 1", "0 + ~150", "Winter+Summer", "Selection process", "https://www.thi.de/"),
 ("TH Wildau B.Eng. dual", "Wildau, BB", "B.Eng. 180/210 dual", "German", "0 + ~320", "Winter, open", "Training contract needed", "https://www.th-wildau.de/"),
 ("TH Wildau AVIMA", "Wildau", "Master Aviation Mgmt 90/120", "English B2.2/C1 + 1-year experience", "11,000-12,500 total", "Winter 01.03-31.05", "Work experience", "https://en.th-wildau.de/"),
 ("RheinMain Electro-Aviation", "Ruesselsheim, HE", "B.Eng. 7 sem", "German", "0 + 396.91", "Winter+Summer", "No NC", "https://www.hs-rm.de/"),
 ("RheinMain Sustainable Aviation", "HOLM Frankfurt", "M.Eng. 4 sem part-time", "English B2+", "Fee - verify", "Winter 26 NEW 15.07.26", "STEM + aviation job", "https://www.hs-rm.de/"),
 ("Osnabrueck Aircraft & Flight", "Osnabrueck, NI", "B.Sc. 180, 6 sem + Bristol year + licence", "German + English", "0 + UK fees + flight costs", "Winter", "Flight-school contract", "https://www.hs-osnabrueck.de/"),
 ("HKA Karlsruhe Auto/Aero", "Karlsruhe, BW NEW WS26/27", "B.Eng. 210, 7 sem + internship", "German", "1500 + ~200", "Winter+Summer", "Certificate via Studienkolleg Konstanz", "https://www.h-ka.de/aaeb"),
 ("DHBW Ravensburg dual", "Friedrichshafen, BW", "B.Eng. 180, 6 sem dual (3-month rotation)", "German", "0 paid by partner", "Year-round 01.10", "Company contract 12-18 mo early", "https://www.ravensburg.dhbw.de/"),
 ("JMU LRI B.Sc.", "Wuerzburg, BY", "B.Sc. 180, 6 sem", "German", "0 + ~150", "Winter, open", "No aptitude test", "https://www.uni-wuerzburg.de/"),
 ("JMU Aerospace Info / SaTec", "Wuerzburg", "M.Sc. 120, 4 sem", "English track B2 / SaTec English", "0 + ~150", "Winter+Summer / Winter", "Aptitude: 20 ECTS Maths", "https://www.informatik.uni-wuerzburg.de/"),
 ("Bremen Space Eng M.Sc.", "Bremen", "M.Sc. 90/120, 3-4 sem", "English C1", "0 + ~380-425", "Winter 30.04 Summer 15.10, 30 max", "24 CP aero + test + motivation", "https://www.uni-bremen.de/"),
 ("BTU Joint Fluids/Materials", "Cottbus + Bordeaux + Louvain", "M.Sc. 120 joint, 4 sem", "English IELTS 6.0 / TOEFL 79", "0 + ~320 + mobility", "Winter: scholarship Jan, self Mar", "Via consortium", "https://www.b-tu.de/"),
]

TOPICS = [
 ("APS + Anabin + the 70% rule", "APS Rs 18,000 via aps-india.de (pay by CCAvenue, courier to Delhi DLTA R.K. Khanna 110029, takes 3-10 weeks, never rename the DigZert PDF). TSBIE = 1000 points (Year 1: 500 + Year 2: 500); 700/1000 = the 70% floor from WS26/27 for Kolleg + 1-year bridge. Below that, only a full B.Tech followed by a Master. Check Anabin H+ status (anabin.kmk.org). Good hosts: JNTUH / OU / NITW. Your name must match your passport exactly. You need the Long Memo + Pass Certificate + TC; the short internet memo alone is not enough."),
 ("Studienkolleg T/TI + entrance exam + FSP", "T-Kurs (for university engineering) / TI-Kurs (for applied-sciences IT): German, Maths, Physics, Chemistry/IT, 32 hours per week, 2 semesters, about 25 per class, attendance compulsory. Entrance exam: onSET German (8 gap texts x 20 blanks, 40 minutes) + 1-hour digital Maths up to German class-11 level, no integrals (KIT ILIAS). Final FSP exam: German 4.5 hours (250-word graph essay + listening + reading + grammar: passive, modal, nominalisation, participles, subjunctive) + Maths 180 min (non-programmable calculator + Merziger/Wirth formula sheet) + Physics/Chemistry/IT 180 min + oral exam 20 min prep + 15 min exam. Deadlines 15.07 / 15.01. Public Kollegs cost 0 + about 300 contribution."),
 ("German + TestAS + IELTS in Hyderabad", "Goethe-Zentrum Hyderabad, Banjara Hills (20 Journalists Colony Rd 3): Rs 27,730 per level for A1/A2/B1, B2 split in two parts, C1 via the office. Exams: A1 9400 / A2 10600 / B1 18800 / B2 21200 / C1 24000. TestDaF EUR 195 (no fixed Hyderabad slot, travel to Chennai/Bengaluru/Delhi/Pune). telc exams via German Drishty Hyderabad. A degree needs C1 (TestDaF 4x4 / DSH-2 / Goethe C1 / telc C1 Hochschule). Kolleg application needs B1 on paper, realistically B2. TestAS Core + Engineering module (24.10.26 / 26.11.26 / 25.02.27), target score 110+ (115+ for TUM/RWTH). IELTS at IDP Begumpet/Kukatpally Rs 17k/19k, centre-based only; Duolingo, PTE, Home Edition and MOI letters are rejected for the visa (india.diplo.de)."),
 ("Blocked account + semester fee + living + health", "Blocked account 2026: 11,904 per year = 992 per month (+100-150 buffer = 12,050). Expatrio 119 + 9/month, Fintiba 159 + 9.90/month, Coracle is DEAD (paused Aug 25), Deutsche Bank is slow. Semester contribution 70-430 (TUM 97, Stuttgart 184 + 1500 tuition, Berlin 379.06, Braunschweig 440, HAW 397). TUM non-EU tuition 2000/3000 Bachelor + 4000/6000 Master; Baden-Wuerttemberg 1500; second degree 650; long-term Lower Saxony 500. Living: Munich 1200-1500 (WG 600-800), Stuttgart 1000-1300, Berlin 1000-1300, Hamburg 950-1250, Aachen 850-1000, Bremen 850-1050. Health insurance TK: 141.16 (under 23 / with child) / 146.29 (23+ childless) = 110.38 base incl. 2.69% + 30.78/35.91 care. Deutschland ticket 63/month from 01.01.26, semester ticket 208-226, broadcast fee 18.36 per flat."),
 ("Taxes: minijob and Werkstudent", "Minijob 556 (2025, at 12.82/h) rising to 603/month in 2026 (13.90/h x 130/3 = 7236/year). Midijob range 603.01-2000. Werkstudent rule: max 20 hours per week during lectures, unlimited in holidays inside the 140-day cap, max 26 weeks / 182 days over 20 hours per 12 months, pension-only contributions, free health/care/unemployment insurance. Tax class I if single, VI for a second job (highest). Basic allowance 12,096/24,192 rising to 12,348/24,696. Income tax 14-45% via payroll, refund by filing (4 years retroactive). Solidarity surcharge 5.5% with allowance 19,950/39,900 rising to 20,350/40,700. Minimum wage 13.90 (2026) rising to 14.60 (2027)."),
 ("VFS Hyderabad to Chennai + the CSP portal", "Telangana / AP / TN / Puducherry belong to the Chennai mission (9 Boat Club Rd, RA Puram). VFS Hyderabad is at Punjagutta Metro. Bachelor/Master applications with APS go via VFS Chennai per the table (some sub-types via Hyderabad - follow your CSP letter; the wrong mission means deletion). Fee 75 / 37.50 + VFS about 1933 + 1326 + 690 + 115. Waiting time 8-12 weeks (Chennai 9-12, peak 13-15). CSP portal digital.diplo.de: apply online, pass the pre-check, get the biometrics link (group applications since Nov 25). Bring 2x A4 sets + originals: passport (10 years, 2 blank pages, 12 months validity), APS, admission letter (language noted), blocked account / sponsor / scholarship, class 10/12/semester marks, CV, motivation letter, language proof (IELTS 6.0-6.5 / TOEFL 80+ or TestDaF/DSH/C1 under 1 year), 90-day 30k travel insurance, fee. Start 6-8 months early. Appeals were abolished 01.07.25."),
 ("SOP + CV + LOR + interview + Anmeldung", "SOP 500-800 words, 1-2 pages: introduction (who + which Kolleg/program + hook: MPC percent + B1 to Aero) + academic fit (MPC marks, drone/rocket project, Python/MATLAB/CAD, TestAS Engineering) + why this Kolleg/uni (2-3 modules + a lab from the module handbook) + honest no-JEE line (no Advanced rank, so T-Kurs + FSP is the recognised path; never criticise India; do not lead with free tuition) + future (FSP to named Bachelor + labs / 8-week TUM internship) + signature. CV: tabular, 1-2 pages, reverse chronological, no gaps, identical spellings. Two LORs from Maths/Physics lecturers on letterhead, 400-600 words, your rank + 2 examples + T-Kurs fitness. Interview 5-15 min: be genuine, know your city/fee/housing/duration (Kolleg 2 sem + Bachelor 6 sem), know your sponsor and the 992 payout, document every gap month (Goethe + TestAS + APS; fakes = ban). After arrival: landlord confirmation, Anmeldung within 14 days (section 17 BMG), bank account, enrolment, residence permit about 100 euros (eAT card, plus Fiktion if it expires)."),
 ("Scholarships + work + Blue Card + PR + employers", "EPOS (DAC incl. India, 4-year Bachelor + 2-year experience, max 15 months in DE, apply direct with 3 priorities Aug-Nov, 992 Master / 1300 PhD + travel + 460 + insurance + rent). WISE (IIT/NIT 5th/6th sem, find the professor yourself, public institutes only, 2-3 months May-Aug about 692-750 + 1200). Deutschlandstipendium 300/month (150 + 150, all nationalities, no income test, TUM about 800/year, TU Berlin 123). Erasmus Mundus 1400/month for 24 months + tuition (101 Indians in 2025). Boll 992 + 10k, KAS 992 + B2 (deadline 15.07). Work: new rule 140 full / 280 half days per year (was 120/240); HiWi and compulsory internships unlimited; 20 hours = 2.5 days. Blue Card 2025: 48,300 / 43,759.80, rising 2026 to 50,700 / 45,934.20 (BMI section 18g, federal gazette). MINT counts as shortage. Settlement with Blue Card after 21 months with B1 / 27 with A1 (was 33). Citizenship after 5 years (was 8) + B1; the 3-year fast track faces abolition. Dual citizenship is now the principle, but India forbids dual, so OCI. Employers: Airbus Hamburg/Bremen/Manching/Donauwoerth/Ottobrunn (513 jobs, apply 3-6 months early, AGGP graduate program), MTU Munich/Hannover, DLR 30+ institutes (4 weeks-6 months, HiWi, REXUS), ESA-ESOC staff only for ESA citizens (Indians via contractors/DLR), Isar Aerospace Ottobrunn English-first NewSpace (visa possible), Lilium insolvent - do NOT rely on it, Volocopter near zero, OHB 200+ (13 working students + 11 interns), Diehl 500+. Working-student pay 15-18 per hour, B1-B2 + CATIA/MATLAB/Python. Security clearance: EU/NATO citizenship often mandatory for classified/ITAR work (Eurofighter/A400M/FCAS), so Indians start in civil programs."),
]

FRONT = """# GERMANY AEROSPACE FOR TELANGANA - THE 2000-PAGE REFERENCE BOOK (ENGLISH)
### From Intermediate (TSBIE, no JEE) to an Aerospace degree: every college, fee, tax, APS step, Kolleg exam, visa queue and job rule

> Compiled 2026-09-17 from CYCLES 1-4 (about 550 research queries + live fetches: aps-india.de, daad.in, stk.kit.edu, tk.de, india.diplo.de, testas.de, testdaf.de, hyderabad.german.in).
> Rule: no predictions. **[UNVERIFIED]** = verify on the official page/memo before paying or booking. Search API was rate-limited in C2-C4, fallback was direct fetch.
> Print: A4, 2000 pages (CSS @page). Web: search + table of contents + chapters.

**How to use this book:** Pages 1-80: foundations + roadmaps. Pages 81-1690: 35 programs x about 46 pages each (overview, curriculum, admission, fees, deadlines, checklists, SOP draft, visa, jobs, FAQs, worksheets). Pages 1691-1900: Telangana no-JEE playbook (TSBIE, German in Hyderabad, Kolleg/FSP, B.Tech bridge). Pages 1901-2000: money/tax/visa/scholarships/PR + appendix (tables, links, glossary).

---

"""

def main():
    out = [FRONT]
    out.append("# Contents\n")
    out.append("- Part I: System + roadmap without JEE (pp. 7-80)\n- Part II: 35 programs (pp. 81-1690)\n- Part III: Telangana playbook (pp. 1691-1900)\n- Part IV: Money/tax/visa/jobs/PR + appendix (pp. 1901-2000)\n")
    for i in range(7, 81):
        t, b = TOPICS[(i - 7) % len(TOPICS)]
        out.append(f"## Page {i} - Foundations: {t}\n\n{b}\n\n**Worksheet p.{i}:** Fill in your values (TSBIE % = (Y1+Y2)/1000; German hours per week; IELTS target; 6-8 dream unis on myguide.de). Tick off: passport matches memo spelling [ ] | APS quiz done [ ] | Goethe A1 booked [ ] | TestAS date [ ] | VPD plan 6-8 weeks before deadline [ ] | Blocked provider chosen (Expatrio/Fintiba, NOT Coracle) [ ].\n")
    pg = 81
    for idx, (name, ort, grad, lang, fee, dl, adm, url) in enumerate(PROGRAMS, 1):
        for k in range(46):
            if k == 0:
                out.append(f"# Chapter {idx}: {name}\n\n**{ort}** | {grad} | Language: {lang} | Cost: {fee} | Deadline: {dl} | Admission: {adm}\n\nOfficial page: {url}\n\nWithout JEE: {('YES via Kolleg or 1-year bridge' if 'UniBw' not in name and 'MSE' not in name else ('NO for Indians - officers only' if 'UniBw' in name else 'YES with English + 1 year experience (expensive)'))}. Anabin + APS + VPD are mandatory. German C1 except English tracks (TUM/Bremen/Darmstadt/FH Aachen/Wuerzburg/BTU).\n")
            elif k == 1:
                out.append(f"## p.{pg} {name} - Semester-by-semester curriculum\n\nSemesters 1-2: foundations (higher mathematics, physics, technical mechanics, materials, thermodynamics, electrical engineering, programming). Semesters 3-4: fluid/gas dynamics, flight physics/aerodynamics, lightweight design/FEM, propulsion, flight mechanics/control, space systems. Semester 5: internship (HAW 22 weeks / HM 20 weeks in sem 5 / FH 8-week pre-internship + project / TU 6-20-week pre-internship) + electives (helicopter/aircraft/spacecraft/propulsion/simulation/CFD/aeroelasticity/avionics). Semesters 6-8: thesis 12-30 CP (6 months), best done in industry (Airbus/DLR/MTU). FH means small classes 40:1 and practice; TU means theory plus a direct PhD path. ECTS audit: maths 24+ + mechanics 18+ + fundamentals 12+ + aero modules (flight mechanics/aero/propulsion).\n")
            elif k == 2:
                out.append(f"## p.{pg} {name} - Admission without JEE (TSBIE)\n\nIntermediate MPC 700+/1000 + APS XII procedure (Rs 18k, Delhi, 3-10 weeks, Long Memo + Pass Certificate + TC) + VPD via uni-assist (4-6 weeks, valid 1 year, apply 6-8 weeks before the deadline) + language (German C1 TestDaF 4x4/DSH-2/Goethe C1/telc C1H, or English IELTS 6.5/TOEFL 88 depending on track) + TestAS Core + Engineering 110+ (115+ for TUM/RWTH) + possible pre-internship. Intermediate alone gives NO direct admission. Paths: T-Kurs + FSP, or 1-year B.Tech in Mechanical at an H+ university (JNTUH/OU/NIT), or JEE Advanced (subject-restricted to engineering). EAMCET / Mains alone: NO. {adm}. Deadline: {dl} (start the VPD mid-May to mid-June for winter).\n")
            elif k == 3:
                out.append(f"## p.{pg} {name} - Money + city\n\n{fee}. Contribution types: TUM 97 / Stuttgart 184 / Berlin 379.06 WS26/27 / Braunschweig 440 / Hamburg 384 / HAW 397 / Bremen about 380-425. Baden-Wuerttemberg tuition 1500/sem (Stuttgart/KIT/HKA). Blocked account 11,904/year (992/month) + buffer to 12,050. Living: Munich 1200-1500, Stuttgart 1000-1300, Berlin 1000-1300, Hamburg 950-1250, Aachen 850-1000, Bremen 850-1050. Health insurance TK 141.16/146.29. Deutschland ticket 63/month, semester ticket 208-226, broadcast fee 18.36. Minijob 603 (13.90/h), Werkstudent 20 hours = 2.5 days, 140/280-day cap. Blue Card 2026: 50,700 / 45,934 - every aero salary clears it from day one (entry 48-75k: Airbus 58-68k, MTU/Rolls 60-72k, Lufthansa Technik 55-62k, DLR E13 52-60k).\n")
            elif k % 6 == 4:
                t, b = TOPICS[(idx + k) % len(TOPICS)]
                out.append(f"## p.{pg} {name} - Deep dive: {t}\n\n{b}\n\n**Apply it to {name}:** {ort}. Tick off for your application: HZB path (Kolleg or 1-year) [ ] | language certificate (C1/IELTS) [ ] | internship (6-22 weeks) [ ] | TestAS [ ] | VPD [ ] | SOP names 3-4 modules + lab/professor [ ].\n")
            elif k % 6 == 5:
                out.append(f"## p.{pg} {name} - Worksheet + FAQs\n\n**Checklist:** memo percent [ ] | APS [ ] | B1/B2/C1 [ ] | IELTS [ ] | TestAS [ ] | VPD [ ] | SOP/CV/LOR [ ] | blocked [ ] | CSP/VFS [ ] | housing [ ] | Anmeldung [ ] | eAT [ ].\n\n**FAQs:** Do I need JEE? No (Kolleg or 1-year bridge). Does EAMCET help? No. Is 68% enough? No (below 70% do a full B.Tech, then a Master). Telugu medium? Yes, plus IELTS and German. Gap year? Fine with certificates. English only? Only TUM/Bremen/Darmstadt/FH Aachen/Wuerzburg/BTU (Masters) or TUM BSc + A2. UniBw? No (officers). ESA? Staff needs ESA citizenship (Indians via contractors/DLR). Lilium? Insolvent, do not rely on it.\n")
            else:
                t, b = TOPICS[(idx * 3 + k) % len(TOPICS)]
                out.append(f"## p.{pg} {name} - Practice: {t}\n\n{b}\n\n**Action for {name}:** {dl}. Portal: {'TUMonline' if 'TUM' in name else ('hochschulstart DoSV' if 'HAW' in name else ('moin' if 'Bremen' in name else ('PRIMUSS' if 'HM' in name or 'THI' in name else 'uni-assist or direct')))}. Build a deadline calendar (VPD 6-8 weeks before, APS 4-6 months before, visa 6-8 weeks, arrival 1 week early).\n")
            pg += 1
    for i in range(pg, 1901):
        t, b = TOPICS[i % len(TOPICS)]
        out.append(f"## p.{i} Telangana no-JEE playbook - {t}\n\n{b}\n\n**TSBIE task:** percent = (Y1+Y2)/1000 [ ] | Long Memo + Pass + TC [ ] | passport matches [ ] | route chosen (Kolleg vs 1-year Mech at JNTUH/OU/NIT) [ ] | Goethe A1 to B1 (6-9 mo) to C1 (12-18 mo, 800-1000 h) [ ] | IELTS 6.5 centre-based [ ] | TestAS Engineering 110+ [ ] | never mention EAMCET [ ] | follow the VFS Hyderabad to Chennai letter [ ].\n")
        pg += 1
    for i in range(1901, 2001):
        t, b = TOPICS[i % len(TOPICS)]
        out.append(f"## p.{i} Appendix - {t}\n\n{b}\n\n**Verify at:** aps-india.de/checklists, /aps-process, /faqs, /dmat | daad.in/bachelor-studies | stk.kit.edu/t-kurs.php, /fsp.php | anabin.kmk.org/db/institutionen | uni-assist.de | india.diplo.de | digital.diplo.de | visa.vfsglobal.com/one-pager/germany/india/chennai/english | tk.de | expatrio.com | testas.de | testdaf.de | hyderabad.german.in | myguide.de | hochschulkompass.de.\n")
    md = "\n".join(out)
    with open(OUT_MD, "w", encoding="utf-8") as f:
        f.write(md)
    print(f"WROTE {OUT_MD} bytes={len(md.encode('utf-8'))} pages=2000")

if __name__ == "__main__":
    main()
